### ISSUE TITLE
Doebox database 

### ISSUE THREAD

**Issue by derhnyel** [doesoft/doebox#4]
Creating a database for the cloud based file manager.

**Comment by abumuhab98** [comment]
are you testing how the issue feature works?

**Comment by derhnyel** [comment]
Yes. I would also like us to start working on various aspect of the project 
Just think of issue you would like to add and add it.

**Comment by abumuhab98** [comment]
what do you suggest we start working on?
the database?
i could start an empty django project for doebox and upload the repository. we can start from there

**Comment by derhnyel** [comment]
That's a great idea. Thanks
